version: "3.9"

services:
  postgres:
    image: "postgres:15.1-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./docker/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    restart: unless-stopped